### ISSUE TITLE
This module is compatible with third-party Checkout?

### ISSUE THREAD

**Issue by rjslegall** [TAGGRS/TAGGRS_Magento2#3]
1. This module is compatible with third-party checkout and success pages, example: Firecheckout?

2. Is Enhanced Conversions only working server side?

**Comment by Webwijs** [comment]
1. It's not tested with third-party checkouts, but please feel free to test it on Firecheckout and report your findings. 
2. I'll get back to you with this answer

**Comment by Webwijs** [comment]
@rjslegall For Enhanced Conversions server side is not mandatory, this can also be done with client side tracking.
